# Variables that contain the user credentials

ACCESS_TOKEN = "PLACE ACCESS TOKEN HERE"
ACCESS_TOKEN_SECRET = "PLACE YOUR ACCESS_TOKEN_SECRET HERE"
CONSUMER_KEY = "PLACE YOUR CONSUMER_KEY HERE "
CONSUMER_KEY_SECRET = "PLACE YOUR CONSUMER_KEY_SECRET HERE"
